package model

//
// ApplicationTag represents a row in the join table for the
// many-to-many relationship between Applications and Tags.
type ApplicationTag struct {
	ApplicationID uint        `gorm:"primaryKey"`
	TagID         uint        `gorm:"primaryKey"`
	Source        string      `gorm:"primaryKey;not null"`
	Application   Application `gorm:"constraint:OnDelete:CASCADE"`
	Tag           Tag         `gorm:"constraint:OnDelete:CASCADE"`
}

//
// TableName must return "ApplicationTags" to ensure compatibility
// with the autogenerated join table name.
func (ApplicationTag) TableName() string {
	return "ApplicationTags"
}
