name: Build Hub

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

concurrency:
  group: main-hub-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true
      - run: make fmt
      - run: make vet

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true
      - run: make test

  test-frontend-lookup-container:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.grepBuilder.outputs.image }}

    steps:
      - uses: actions/checkout@v7

      - name: Lookup frontend image builder from the project's Dockerfile
        id: grepBuilder
        run: |
          image=$(grep -i 'as frontend' Dockerfile | sed -e 's/^from \(.*\) as frontend$/\1/i')
          echo "image=${image}" >> "$GITHUB_OUTPUT"

  test-frontend:
    needs: test-frontend-lookup-container
    runs-on: ubuntu-latest
    container: ${{ needs.test-frontend-lookup-container.outputs.image }}
    steps:
      - uses: actions/checkout@v7

      - name: Install
        working-directory: internal/frontend/auth/content
        run: |
          npm version
          npm clean-install --ignore-scripts --no-audit

      # TODO: Add linting when it's available
      # TODO: Add unit tests when they're available

      - name: Build
        working-directory: internal/frontend/auth/content
        run: |
          npm run build

  # ───── disconnected binding tests ─────
  test-binding:
    needs:
      - lint
      - test-unit
      - test-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - uses: ./.github/actions/start-hub
        with:
          disconnected: 'true'
          auth-required: 'true'

      - name: Run binding tests
        run: HUB_BASE_URL=http://localhost:8080 make test-binding

  # ───── operator level integration tests ─────
  build-image:
    needs:
      - test-binding
    runs-on: ubuntu-latest
    env:
      IMG: ttl.sh/konveyor-hub-${{ github.sha }}:2h
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true
      - run: make cmd
      - run: make docker-build
      - run: docker push ${IMG}

  test-integration:
    needs: build-image
    uses: konveyor/ci/.github/workflows/global-ci-bundle.yml@main
    with:
      tackle_hub: ttl.sh/konveyor-hub-${{ github.sha }}:2h
      api_hub_tests_ref: ${{ github.ref }}
