name: 'Build and Push Multi-Arch Image'

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release-*'
    tags:
      - 'v*'

concurrency:
  group: march-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push-quay:
    name: Build and Push Manifest
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    uses: konveyor/release-tools/build-push-images.yaml@main
    with:
      registry: "quay.io/konveyor"
      image_name: "tackle2-hub"
      containerfile: "./Dockerfile"
      architectures: '[ "amd64", "arm64" ]'
