name: 'Build and Push Multi-Arch Image'

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release-*'
    tags:
      - 'v*'

concurrency:
  group: march-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push-quay:
    name: Build and Push Manifest
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
    - name: Checkout Push to Registry action
      uses: konveyor/release-tools/build-push-quay@main
      with:
        architectures: "amd64, arm64, ppc64le, s390x"
        containerfile: "./Dockerfile"
        image_name: "tackle2-hub"
        image_namespace: "konveyor"
        image_registry: "quay.io"
        extra-args: |
          --build-arg SEED_BRANCH=${{ github.ref_name }} --build-arg STATIC_REPORT_TAG=${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
        quay_publish_robot: ${{ secrets.QUAY_PUBLISH_ROBOT }}
        quay_publish_token: ${{ secrets.QUAY_PUBLISH_TOKEN }}
        ref: ${{ github.ref }}
